version: '3.7'
services:

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./web/conf/conf.d:/etc/nginx/conf.d

  web-node-1:
    build: ./images/php
    ports:
      - "8001:80"
    volumes:
      - ./www/foo:/var/www/html

  web-node-2:
    image: php:7.2-apache
    ports:
      - "8002:80"
    volumes:
      - ./www/bar:/var/www/html

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    env_file:
      - mariadb.env
#    environment:
#      MARIADB_ROOT_PASSWORD: r00tP@ss
#      MARIADB_DATABASE: test_db
#      MARIADB_USER: test-admin
#      MARIADB_PASSWORD: test_pass
    volumes:
      - ./databases/mariadb:/var/lib/mysql
